### ISSUE TITLE
Include MadGraph5 in the container

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/docker#13]
## Is your request related to a problem? Please describe.
Users need to use MadGraph to generate specific vertices that they need to use with ldmx-sw.
Having a derivative that has MadGraph installed would allow a user to always use the container when working on ldmx.

[MadGraph5@NLO](https://launchpad.net/mg5amcnlo)

## Describe the solution you'd like. What packages do you want installed?
Unpack and install MadGraph on top of the current base development container.

**The Development Container is based on Ubuntu 18.04. How do you install your necessary packages on Ubuntu?**
_untested_: I believe unpacking the python source is all that is necessary.
```
wget https://launchpad.net/mg5amcnlo/2.0/2.7.x/+download/MG5_aMC_v2.7.3.py3.tar.gz
tar xvf MG5_aMC_v2.7.3.py3.tar.gz
```

**Comment by tomeichlersmith** [comment]
@sophiemiddleton I created the docker container and pushed it to the docker hub. Can you test it out and put your results here?

## with docker:
```
docker pull ldmx/dev:madgraph
docker run --rm -it -v $(pwd):/work -u $(id -u $USER):$(id -g $USER) /work <command-to-run>
```

## with singularity
```
singularity build ldmx-dev-madgraph.sif docker://ldmx/dev:madgraph
singularity run --no-home ldmx-dev-madgraph.sif . <command-to-run>
````

**Comment by tomeichlersmith** [comment]
I have been able to run `mg5_aMC` by unpacking the MadGraph5@NLO source outside of the container but inside my `$LDMX_BASE` directory. So MadGraph is still outside the container, but we run MadGraph inside the container. i.e.:
```
source ldmx-sw/scripts/ldmx-env.sh
cd $LDMX_BASE
wget https://launchpad.net/mg5amcnlo/2.0/2.7.x/+download/MG5_aMC_v2.7.3.tar.gz
tar xvf MG5_aMC_v2.7.3.tar.gz
cd MG5*
ldmx ./bin/mg5_aMC
#enter MG5 shell without any fatal errors (but several warnings)
```
So maybe we don't need to create a whole new container?

**Comment by sophiemiddleton** [comment]
I agree I think the above is sufficent.

**Comment by tomeichlersmith** [comment]
Ok, going to mark this as closed but leave the branch just in case we need it in the future.
