### ISSUE TITLE
Separate ROOT into lighter base container

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/docker#14]
With plans to separate the modules into optional components, we can also separate the dependencies of the different modules so that those who don't need Geant4+XercesC don't have to be slowed down by one of those containers.

We can have a foundation container with ROOT (maybe with several different versions/build options?) and then we can build the simulation dependencies on top of it.

**Comment by tomeichlersmith** [comment]
Great news! ROOT has updated its docker image finally:

**Comment by tomeichlersmith** [comment]
Nope! ROOT doesn't build against C++17 by default, so we can't use their docker images :/

**Comment by omar-moreno** [comment]
Maybe we can request one? :)

**Comment by tomeichlersmith** [comment]
The reason I don't think that is feasible is because they make the docker image by downloading a release's precompiled binary archive. _All_ of the release's precompiled binary archives are built with the default configuration. :/

I will look into it a little bit more, but I think we will have to make keep compiling our own.
