### ISSUE TITLE
python2 extra tools container

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/docker#16]
## Is your request related to a problem? Please describe.
Need `uproot`, `numpy`, and `matplotlib` installed on a container with PyROOT built using python2

Just want a place to keep track of the progress on this.

**Comment by tomeichlersmith** [comment]
On the `iss16` branch, I was able to make a docker file `derivatives/Dockerfile.py2tools` that seems to be working:
```
tom@sokka:~/ldmx$ source ldmx-sw/scripts/ldmx-env.sh . py2tools local
will assume locally built container: py2tools 
tom@sokka:~/ldmx$ ldmx python
Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot
>>> import numpy
>>> import matplotlib
>>> quit()
```
But obviously `import` doesn't actually test what you need. Hopefully this is a good place to start from though.

**Comment by bryngemark** [comment]
this looks good, the Dockerfile looks right
