### ISSUE TITLE
Conditions test using deprecated link

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/docker#27]
**Describe the bug**
The automatic tests are failing because the Conditions test is unable to access the CSV table at the http link that @jmmans provided: http://webusers.physics.umn.edu/~jmmans/test_table.csv

I know that UMN has been implementing some updates to the website; this may affect how our homepages are accessible.

**To Reproduce**
1. Observe the failure of the GitHub test action
2. Scroll down to see 
```
-------------------------------------------------------------------------------
Conditions
  Testing HTTP loading
-------------------------------------------------------------------------------
/home/runner/work/ldmx-sw/ldmx-sw/Conditions/test/TestConditions.cxx:170
...............................................................................

/home/runner/work/ldmx-sw/ldmx-sw/Conditions/test/TestConditions.cxx:170: FAILED:
due to unexpected exception with message:
  Too much redirection in attempt to load HTTP CSV file
```

**Potential Fix**
I think we just need to update the link or move the test csv to a new location.

**Comment by tomeichlersmith** [comment]
Following this guide on stack-exchange: https://askubuntu.com/a/649463

**Comment by tomeichlersmith** [comment]
I am able to `wget` the table now using:
```
ldmx wget  http://webusers.physics.umn.edu/~jmmans/test_table.csv
```
But the test still fails:
```
-------------------------------------------------------------------------------
Conditions
  Testing HTTP loading
-------------------------------------------------------------------------------
/home/tom/ldmx/ldmx-sw/Conditions/test/TestConditions.cxx:170
...............................................................................

/home/tom/ldmx/ldmx-sw/Conditions/test/TestConditions.cxx:170: FAILED:
due to unexpected exception with message:
  Null condition returned for requested item : test_table_http
```
This is after changing the URL in the test to ` https://homepages.spa.umn.edu/~jmmans/test_table.csv` because otherwise the "too much re-direct" error would be thrown.

**Comment by jmmans** [comment]
Dear Tom,

This looks like a different sort of failure, indeed -- I'd like to 
debug.  I tried to run the process you gave on my own docker image and 
that didn't work -- there was no sudo.

Jeremy

**Comment by jmmans** [comment]
Unfortunately, this doesn't really solve it.  The problem is that my 
code doesn't actually handle HTTPS right now, only HTTP.

I can try to get HTTPS working, but it is definitely more complex.  I 
also tried to set up a horrible hack using system() and wget, but that 
failed...

Jeremy

**Comment by tomeichlersmith** [comment]
Is there a container-level fix that you can think of? Or is this a UMN-server issue that needs to be resolved?

Another idea: Maybe try having the python class do the downloading? That might allow you to access `wget` or a more pythonic solution easier.
