### ISSUE TITLE
ACTS Library version 14.0.1

### ISSUE THREAD

**Issue by pbutti** [LDMX-Software/docker#36]
## Is your request related to a problem? Please describe.
Currently we use ACTS v8.2.0. Several additions have been made to the library since then. Since I'm diving into this daily I'd like to develop directly with the latest API, if possible. 

## Describe the solution you'd like. What packages do you want installed?
I would like to bump the ACTS version to 14.0.1

**Additional context**

**Comment by tomeichlersmith** [comment]
I just pushed another commit to bump up the version. Yesterday's build pushed a version of the container with ACTS v9.1.0, so if you re-pull the container image, you can play with that version now.

Would it be beneficial to have you build ACTS with the container (but outside of it) similar to how we build ldmx-sw? The container is really meant to pick a version and freeze it there, so if you forsee more ACTS "bumping" that might be the best intermediate solution. A simple way to do this is to have ACTS installed to a specific directory (e.g. `${LDMX_BASE}/acts/install`) similar to how ldmx-sw is installed to a specific directory (e.g. `${LDMX_BASE}/ldmx-sw/install`).

**Comment by tomeichlersmith** [comment]
Build for ACTS v14.1.0 going on here: https://github.com/LDMX-Software/docker/actions/runs/1417225347

**Comment by pbutti** [comment]
Hi Tom, 

thank you for the fast reply and help with this. Uhm, I don't know how often I expect the library to change.. I hope it's starting to converge. I just requested because I noticed that we are behind of 6 versions, and looking at the latest releases some of the API changed. 

It could be a good idea to have it externally. I do like it in the container at the moment cause it's much easier for me to develop, but I like your proposal.

**Comment by tomeichlersmith** [comment]
Ok, I will let you know when I have a solution.

**Comment by tomeichlersmith** [comment]
The current container that you are using adds externals installed along side ldmx-sw to the `LD_LIBRARY_PATH`. This is to accomodate the fact that we download and unpack a pre-compiled onnx-runtime but you could use this to have a "external" build of ACTS. I haven't tried this yet, but I think building ACTS would then go like:
```
# the acts source code needs to be in a directory that the container can "see"
cd acts
ldmx mount .
ldmx cmake -DACTS_BUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=${LDMX_BASE}/ldmx-sw/install/external/acts -DCMAKE_CXX_STANDARD=17 -B build -S .
cd build
ldmx make install
```
Then you would need to tell ldmx-sw to use your ACTS rather than the one installed inside the container. I'm assuming this is something cmake related, although again, unable to test.
```
cd ldmx-sw/build
ldmx cmake -BACTS_DIR=${LDMX_BASE}/ldmx-sw/install/external/acts ..
```

**Comment by pbutti** [comment]
Hey Tom! Thank you. Yes I think I could test this tomorrow, to know if it will work, but I think we can stay with the 14.1.0 docker when ready for a while. But sure, I'll check =) Thank you!

**Comment by tomeichlersmith** [comment]
Speaking of, the build just finished! (It had a lot of the lower layers cached from yesterday so it could skip those.)
You can re-pull the container image to get the newer version:
```
ldmx pull dev dd4hep-acts
```
I also tag the images with[ the commit sha ](https://hub.docker.com/r/ldmx/dev/tags?page=1&ordering=last_updated)that generated them so you can switch to an older ACTS if need be:
```
ldmx pull dev sha-caa35b55 # ACTS v9.1.0 - yesterday's build
ldmx pull dev sha-995b3239 # ACTS v14.1.0 - today's build
```

**Comment by omar-moreno** [comment]
We can always add a CMake option to download the specified version of ACTS
and build it on the fly. It won't be the default but may be useful for
testing.

**Comment by pbutti** [comment]
ldmx pull dev sha-995b3239 seems to point to master
