### ISSUE TITLE
clang-format

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/docker#47]
## Is your request related to a problem? Please describe.
We keep saying to "format your code" but we already have a method of providing a formatter for everyone developing ldmx-sw.

## Describe the solution you'd like. What packages do you want installed?
clang-format

**The Development Container is based on Ubuntu 18.04. How do you install your necessary packages on Ubuntu?**
A description and list of commands to run, for example
```
apt-get install clang-format
```

**Comment by EinarElen** [comment]
+1 on this. Maybe we could also add a .clang-format file to our repos (I'm not sure if its enough to keep one in ldmx-sw?) so that the default will pick the formatting style we want. I remember seeing somewhere that we were supposed to rely on the google style, which I don't think is the default

**Comment by bryngemark** [comment]
+1 
Is it possible/wise/dangerous to make formatting part of the PR action?
