### ISSUE TITLE
some python plotting packages

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/docker#50]
## Is your request related to a problem? Please describe.
Want to be able to run some automated validation plotting in the container

## Describe the solution you'd like. What packages do you want installed?
`mplhep` please

**The Development Container is based on Ubuntu 18.04. How do you install your necessary packages on Ubuntu?**
A description and list of commands to run, for example
```
mplhep # in python pip list
```

**Additional context**
https://github.com/LDMX-Software/ldmx-sw/pull/1122

**Comment by bryngemark** [comment]
Add `pandas` to this list
