### ISSUE TITLE
multi-platform image building

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/docker#55]
Too many users have fancy-shmancy computers with Apple's M1 ARM chip, so we need to build multiple platform images now.

I think this will be easy to update our GitHub actions, but I need to figure out a way to update test them.

https://docs.docker.com/build/ci/github-actions/multi-platform/

## To Do
- [x] build successfully in parallel here - non-native arch builds take too long so we need #61 to do this successfully
- [x] add custom image tags
- [x] add method of testing
- [x] check that the arm64 image works on arm64 @therwig 
- [x] check that `apptainer` still functions properly (at UMN)
- [x] check that `singularity` still functions properly (at SLAC)

---

Doing development of this GitHub workflow in a different repository so I can more quickly engage in development cycles unrelated to the compiling of all our dependencies. https://github.com/tomeichlersmith/ldmx-multi-arch-test/tree/main
This pushes images to DockerHub at `tomeichlersmith/ldmx-multi-arch-test`.

**Comment by tomeichlersmith** [comment]
Add in a build-from-source onnx runtime install.

https://onnxruntime.ai/docs/build/inferencing.html

**Comment by tomeichlersmith** [comment]
The GitHub builds are failing for obscure reasons, I think the only way forward from here is to collaborate with a person with an ARM chip or devote time to learning how `docker buildx` operates and use it locally to make sure both architectures can be built by our Dockerfile.

**Comment by bryngemark** [comment]
@tomeichlersmith @therwig was this resolved/what is needed to make progress? in light of the upcoming major changes to our container (https://github.com/LDMX-Software/docker/pull/54), is this a good time to get this functionality in?

**Comment by tomeichlersmith** [comment]
I think this is a good time to at least attempt to put this in. I don't want to wait for weeks to try to figure this out but I'll put some hours in trying to use `docker buildx` to see if I can get this working.

With that in mind, I'm going to create a "milestone" for this release so that we don't have to keep all the work on one branch with one PR.

**Comment by tomeichlersmith** [comment]
I am removing this issue from the v4.0 milestone due to the cascade of requirements below that led this to become a much larger problem.

1. In order to build across architectures, we need to have a per-architecture build of ONNX.
2. Building ONNX from source pushes the GitHub action build time over the 6hr maximum so we can't build it from source.
3. ONNX broke its C++ API between the version we currently use (v1.2.0) and its current version (v1.15.0), so we have to stay at the older version.
4. The old version does not have a ARM pre-build.

This leaves us with two options.

1. Update ldmx-sw to use the newer ONNX version and use pre-builds for both architectures in the Dockerfile.
2. Expand the length of time available for ONNX to build by shortening other build steps (difficult), splitting the build across multiple jobs (complicated), or attaching a self-hosted runner to this repository (costs money).

I am going to option (1) but since this requires further changes to ldmx-sw, I am unsure if I can include this in v4.0.0 of the container image.

**Comment by tomeichlersmith** [comment]
**Status Update** The current Dockerfile takes more than 6hrs to build for the arm64 target architecture while the build for amd64 only takes ~3.5hrs. I suppose this makes sense since most of the GitHub runners are amd64 and building with the same native and target architectures allows docker to skip sending commands through a (slower) VM. My current plan is the following

1. Merge in the refactored GitHub workflows (without arm64 target being built)
2. Put the arm64 target on its own branch
3. https://github.com/LDMX-Software/docker/issues/61 - we have a few extra desktop towers at UMN and I think I can use one of them to be the image builder which would allow the builds to take as long as they need.

**Comment by therwig** [comment]
I haven't totally followed the progress here (can it still proceed despite troubles building onnx?), but would like to help test if its still useful.

**Comment by therwig** [comment]
I ran
```
ldmx $ docker pull tomeichlersmith/ldmx-multi-arch-test:main
main: Pulling from tomeichlersmith/ldmx-multi-arch-test
b2837baf7808: Pull complete 
1f842680a899: Pull complete 
Digest: sha256:f72c8299f8f6808101519c1c64cc7f4e308fe8f07e2e6b8905c0885317a2f5fe
Status: Downloaded newer image for tomeichlersmith/ldmx-multi-arch-test:main
docker.io/tomeichlersmith/ldmx-multi-arch-test:main
ldmx $ docker run --rm tomeichlersmith/ldmx-multi-arch-test:main uname -a
Linux 47b33e7d546e 5.10.104-linuxkit #1 SMP PREEMPT Wed Mar 9 19:01:25 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by tomeichlersmith** [comment]
Awesome :raised_hands: than you @therwig 

This confirms my strategy is correct. The main issue right now is how long it takes to build the non-native architecture images. I am working on getting a self-hosted runner up and running here at UMN so that we can let the image build take as long as it needs.

**Comment by therwig** [comment]
OK great! Can I also ask you where to find general instructions for building a docker image for my machine and then tagging it in a way to make accesible via `ldmx use ...` ? As usual, slack ate my old instructions and I am not finding the info here where I expected it:
https://ldmx-software.github.io/docs/custom-production-image.html
Sorry I'm probably missing something obvious...

**Comment by tomeichlersmith** [comment]
No worries, I don't think there is a page unfortunately which I should probably fix.
---

The docker tags on your computer are separate from the tags on DockerHub and, since you don't have push access to DockerHub, you can just use the same tags. The ldmx-env script expects tags of the form `ldmx/<repo>:<tag>` where `<repo>` is `dev`, `pro`, or `local` and `<tag>` is some string specifying the tag.

**What I would suggest** is to use the `local` repo to make sure that future you remembers that you had to manually build this image.
```
cd docker
docker build . -t ldmx/local:manual-build
# edit ldmx-sw/.ldmxrc to say `use local manual-build` rather than `use dev latest`.
. ldmx-sw/scripts/ldmx-env.sh
```
You could get around editing the `.ldmxrc` by just tagging your manual build as `ldmx/dev:latest`.

**Comment by therwig** [comment]
Trying my hand at getting something to build on my M1 machine. There was trouble with ONNX 1.2.0 but I've gone ahead and tried the 1.15.0 binary, which seems to be working well so far.  I've built the docker image making the following small edits to the Dockerfile
```
-LABEL onnx.version=1.2.0
+LABEL onnx.version=1.15.0
 #RUN mkdir -p src &&\
 #    ${__wget} https://github.com/microsoft/onnxruntime/archive/refs/tags/v1.15.0.tar.gz |\
 #      ${__untar} &&\
@@ -374,12 +374,14 @@ RUN set -x ;\
     ARCH="$(uname -m)" &&\
     if [ "x86_64" = "$ARCH" ]; then \
       onnx_arch="x64"; \
+    elif [ "aarch64" = "$ARCH" ]; then \
+      onnx_arch="aarch64"; \
     else \
       exit 0; \
     fi &&\
     mkdir -p src &&\
     release_stub="https://github.com/microsoft/onnxruntime/releases/download" &&\
-    onnx_version="1.2.0" &&\
+    onnx_version="1.15.0" &&\
     ${__wget} ${release_stub}/v${onnx_version}/onnxruntime-linux-${onnx_arch}-${onnx_version}.tgz |\
```
Will ping here again if I get ldmx-sw to build too

**Comment by tomeichlersmith** [comment]
Notes for future me

---

1. Make sure to resolve cache replication issues.
    - [Cache management with GitHub actions](https://docs.docker.com/build/ci/github-actions/cache/#local-cache) highlights a bug in the interaction between the build-push action and buildx causing the cache to write copies of layers when exporting. They provide a workaround.
3. Try `mode=max` to see if layers can be stored even if full build fails.
    - [Cache storage backends](https://docs.docker.com/build/cache/backends/#cache-mode) makes it seem like the `max` mode will store layers from "intermediate steps" which gives me hope

**Comment by tomeichlersmith** [comment]
I did a quick test and it looks like building within an arm VM is not noticeably faster than building with docker's emulation. I suppose I should have expected this since the VM uses qemu to emulate an arm chip same as docker. With this in mind, I am going to return to a single VM with multiple runners and a layer cache directory that is separated by platform.

**Comment by tomeichlersmith** [comment]
The [first full build in parallel](https://github.com/LDMX-Software/docker/actions/runs/5730733030) passed the tests and pushed arm+amd manifest to dockerhub!

@therwig Can you try this new image and report back here if it works the same as the one you built locally?
```
ldmx use dev 55-multi-platform-image-building
```

**Comment by therwig** [comment]
Hi @tomeichlersmith it appears to work perfectly 😃  I rebuilt locally and ran some of my usual reconstruction scripts.
