### ISSUE TITLE
Clang based development tools

### ISSUE THREAD

**Issue by EinarElen** [LDMX-Software/docker#64]
## Is your request related to a problem? Please describe.
We are currently building our setup with GCC which means we get our static analysis primarily from GCC. Enabling us to make use of other tools (clang and clang-tidy) would be useful, especially if we can integrate it into the early parts of the CI chain (e.g. on push). I've been testing that this plays nicely with LDMX-sw over in https://github.com/LDMX-Software/SimCore/issues/49 and https://github.com/LDMX-Software/cmake/issues/17 and with one exception (I'll open up a separate issue for this), it works great.  

I would also think it would be good to have ccmake, the ncurses interface to the CMake cache. It is super handy if you need to check what variables are set to what or if you just need to change one or two of them. 

## Describe the solution you'd like. What packages do you want installed?

**The Development Container is based on Ubuntu 18.04. How do you install your necessary packages on Ubuntu?**
A description and list of commands to run, for example
```
apt-get install clang clang-tidy clang-tools lld cmake-curses-gui
```

**Additional context**

**Comment by tomeichlersmith** [comment]
Resolved with #67
